version: '3.9'
services:
  mys:
    image: mysql:8.0
      # cap_add:
      # - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=zusammen
      - MYSQL_ROOT_PASSWORD=zusammen-network
    ports:
      - '3306:3306'
    volumes:
      - mys:/var/lib/mysql
  migrate:
    image: migrate/migrate
    restart: on-failure
#    volumes:
#      - ./migrations:/migrate
    command:
      [ "-database",  "mysql://root:zusammen-network@tcp(127.0.0.1:3306)/zusammen" , "-path", "internal/infrastructure/database/migration", "up" ]
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass root
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  mys:
    driver: local
  redis:
    driver: local
